[package]
name = "listening-history-module"
group = "music-connect-team"
version = "0.1.0"
apiVersion = "0.1.0"
description = ""
license = "Apache-2.0"
visibility = "public"

[[params]]
name = "input"
description = "input description"
